config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'

  get 'errors/internal_server_error'

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations'  }
  devise_scope :user do
    get '/users', to: 'users/registrations#new'
    get '/users/sign_out', to: 'users/sessions#destroy'
  end

  resources :tags, only: [:index, :show, :create] do
    member do
      post '/rename-tagname', action: 'rename_tag'
    end
  end
  resources :purchases, only: [:create, :index] do
    collection do
      get '/confirm-purchase', action: 'confirm_purchase'
    end
  end
  resources :subscribers, only: [:new, :create]
  post '/stripe/webhooks', to: "stripe#webhooks"

  get '/merchandise', to: 'site#merchandise', as: :merchandise
  get '/dashboard', to: 'site#dashboard', as: :dashboard
  get '/category/:name', to: 'site#category', as: :category
  get '/contact-us', to: 'site#contact_us', as: :contact_us
  post '/send-email', to: 'site#send_email', as: :sent_email
  get '/terms', to: 'site#terms', as: :terms
  get '/about-us', to: 'site#about_us', as: :about_us

  get '/like-button/:tag_name', to: 'peng_widget#tag_name'
  get '/like', to: 'peng_widget#like'
  get '/page-like-count', to: 'peng_widget#page_like_count'

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  root to: 'site#index', as: :root
end

app/views/shared/_flash_messages.html.haml
- flash.each do |type, message|
  %div{:class => "alert #{bootstrap_class_for(type)} fade in"}
    = message

app/views/shared/_footer.html.haml
.footer
  .footer-links
    =link_to 'Contact Us', contact_us_path
    \-
    =link_to 'Advertise', contact_us_path
    \-
    =link_to 'About Us', about_us_path
    \-
    =link_to 'Terms', terms_path
  .footer-company
    Gorilla Theory Labs 2017

  :javascript
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-96484367-1', 'auto');
    ga('send', 'pageview');

app/views/shared/_main_logo.html.haml
.top-main-image
  .container
    .row
      .col-md-12
        .main-image-logo
          = link_to root_path do
            = image_tag('certifiedpeng-large.png', :class => "main-logo")

app/views/shared/_meta_homepage.html.haml
<meta http-equiv=“Pragma” content=“no-cache”>
<meta name=“Description” CONTENT=“Certified Peng – the content popularity engagement button. Click to rate content as being PENG.“>
<meta name=“Keywords” CONTENT=“peng, certified peng, millennials, millennials marketing, snapchat marketing, snapchat, chicken connoisseur, crep check Instagram, pengest munch.“>
<meta name=“Key-phrases” content=“certified peng, peng, lit, top peng, pengest, pengness, millennials, millennials marketing, snapchat marketing.“>
<meta name=“content” content=“peng, pengness, certified peng, crep check uk, peng creps, best sneakers, pengest munch”>
<meta name=“peng” content=“peng, certified peng, peng london, top peng, rated peng, crep check uk, peng creps, creps, crep, crep lovers, sneakers, crep check, pengest creps, pengest, crep check shoes, crep check chicken connoisseur, crep check jd sports, crep check Instagram, pengest munch.“>
<meta name=“peng instagram” content=“instagram, top pen on instagram,crep check uk, peng creps, creps, crep, fashion, sneaker fashion, pengest creps, pengest, crep check shoes, crep check chicken connoisseur, crep check jd sports, crep check Instagram, pengest munch.“>
<meta name=“msnbot” content=“index,follow”>
<meta name=“googlebot” content=“index,follow”>
<meta name=“robots” CONTENT=“all”>
<meta name=“author” CONTENT=“www.certifiedpeng.com“>
<meta http-equiv=“expires” CONTENT=“never”>
<meta name=“distribution” CONTENT=“global”>
<meta property=“og:title” content=“Certified Peng”>
<meta property=“og:url” content=“https://www.certifiedpeng.com”>
<meta property=“og:description” content=“Certified Peng – the new millennials content engagement popularity metric. Rate content and products as peng and create trends.“>
<meta property=“og:site_name” content=“certifiedpeng.com”>
<meta property=“og:image” content=“http://www.pengcreps.co.uk/images/certifiedpeng-share-sticker.jpg”>
<meta property=“og:type” content=“article”>

app/views/shared/_navbar.html.haml
.top-header
  .row
    .col-md-12
      .navbar-links
        - if !current_user
          = link_to 'Home Page', root_path
          = link_to 'Signup', new_user_registration_path
          = link_to 'Login', user_session_path
        - else
          = link_to 'Dashboard', dashboard_path
          = link_to 'Merchandise', merchandise_path
          = link_to 'My Tags', tags_path
          = link_to 'Purchases', purchases_path
          = link_to 'Logout', destroy_user_session_path, method: :delete