config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'

  get 'errors/internal_server_error'

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations'  }
  devise_scope :user do
    get '/users', to: 'users/registrations#new'
    get '/users/sign_out', to: 'users/sessions#destroy'
  end

  resources :tags, only: [:index, :show, :create] do
    member do
      post '/rename-tagname', action: 'rename_tag'
    end
  end
  resources :purchases, only: [:create, :index] do
    collection do
      get '/confirm-purchase', action: 'confirm_purchase'
    end
  end
  resources :subscribers, only: [:new, :create]
  post '/stripe/webhooks', to: "stripe#webhooks"

  get '/merchandise', to: 'site#merchandise', as: :merchandise
  get '/dashboard', to: 'site#dashboard', as: :dashboard
  get '/category/:name', to: 'site#category', as: :category
  get '/contact-us', to: 'site#contact_us', as: :contact_us
  post '/send-email', to: 'site#send_email', as: :sent_email
  get '/terms', to: 'site#terms', as: :terms
  get '/about-us', to: 'site#about_us', as: :about_us

  get '/like-button/:tag_name', to: 'peng_widget#tag_name'
  get '/like', to: 'peng_widget#like'
  get '/page-like-count', to: 'peng_widget#page_like_count'

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  root to: 'site#index', as: :root
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :user

  MAX_TAGS_COUNT = 15
  TAGS_COUNT = 5
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :authenticate_user!

  def index
    @not_added_tags = Tag::TAGS_COUNT - current_user.tags.count
    @purhace_tags = Tag::MAX_TAGS_COUNT - current_user.tags.count
    @tags = current_user.tags
  end

  def create
    error = get_error(params[:tag])
    if error
      flash[:error] = error
    else
      Tag.create(tag_name: params[:tag], user_id: current_user.id)
        if !current_user.admin? && current_user.limits_of_tags?
          flash[:alert] = 'You have reached your limit of Certified Peng tracking tag allowance'
        end
    end
    redirect_to tags_path
  end

  def show
    @tag = Tag.find_by_id(params[:id])
  end

  def rename_tag
    @tag = Tag.find_by_id(params[:id])
    likes = Like.find_by_tag_name(@tag.tag_name)
    if likes
      flash[:error] = "This tag already has 'likes' and you can not edit this tag"
    elsif !@tag.edited && !likes
      @tag.update_attributes(tag_name: params[:tag], edited: true)
      flash[:notice] = 'Your tag was successfully updated'
    elsif @tag.edited
      flash[:error] = 'You can edit tag only once'
    end
    redirect_to tag_path
  end

  private

  def get_error(tag)
    if !current_user.admin? && current_user.limits_of_tags?
      'You cant add more tags'
    elsif tag.include?(' ') || tag.include?(',')
      'Tag must not contain spaces or commas'
    elsif Tag.exists?(tag_name: tag)
      'Tag you entered already exists'
    end
  end
end

app/helpers/tag_helper.rb
module TagHelper
end

app/views/tags/index.html.haml
%h1.text-center
  Your Tags
%p.text-center
  - if current_user.admin?
    You can add an unlimited number of tags
  - elsif !current_user.admin? && current_user.exist_purchase?
    You have made purchases and you can add more tags - #{@purhace_tags}
  - else
    You can track 5 Tags per account. You can still add #{@not_added_tags} tags

.new-tag
  .row
    .col-lg-4.col-md-3.col-xs-0
    .col-lg-4.col-md-6.col-xs-12
      = form_tag tags_path do
        .input-group
          = text_field_tag 'tag', nil, placeholder: "Enter one tag each", class: 'form-control'
          %span.input-group-btn
            = submit_tag 'Add tag',class: 'btn btn-default'
    .col-lg-4.col-md-3.col-xs-0

.row
  .col-lg-3.col-md-2.col-xs-0
  .col-lg-6.col-md-8.col-xs-12
    .tags-box
      .list-group
        - @tags.each do |tag|
          .list-group-item{:href => "#"}
            = link_to tag.tag_name, tag_path(tag)
  .col-lg-3.col-md-2.col-xs-0

app/views/tags/show.html.haml
%h3.text-center
  Edit your tag:
%p.text-center
  You can edit your tag only once
.new-tag
  .container
    .row
      .col-md-4
      .col-md-4
        = form_tag rename_tagname_tag_path do
          .input-group
            = text_field_tag 'tag', @tag.tag_name, class: 'form-control'
            %span.input-group-btn
              = submit_tag 'Edit',class: 'btn btn-default'
      .col-md-4
    %hr

.script-container
  .container
    .row
      .col-md-2
      .col-md-8
        .panel-group
          .panel.panel-default
            .panel-body
              %h4.text-center
                Get the Certified Peng button for your content using your TAG - #{@tag.tag_name}:
            .panel-heading{style: 'color: #615e5e; font-size: 15px;'}
              = "<div class='sinatra-like-button'>"
              %br
              = "  <script src='https://www.certifiedpeng.com/like-button/#{@tag.tag_name}' type='text/javascript'></script>"
              %br
              = '</div>'
      .col-md-2
    %hr

.text-container
  .row
    .col-md-3
    .col-md-6
      %b How To:
      %br
      %b Step 1:
      Copy and paste the code snippet above
      %br
      %b Step 2:
      Place the code where you want the Certified Peng button to appear on your web page
      %br
      %b Step 3:
      Upload your web page and watch the clicks count increase
      %br
      %b NB:
      %span
        You can have a Certifed Peng button without adding having a tracking account, but you will not be able to access the
        = link_to 'tracking dashboard', new_user_session_path
        where you can create specific tags for campaigns or specific content
      %br
      %b Advanced - for tag tracking
      %br
      %b Step 4:
      %span
        = link_to 'Register', new_user_registration_path
        for a Certified Peng tracking account:
        = link_to 'click here >', new_user_registration_path
      %br
      %b Step 5:
      %span
        = link_to 'Login', new_user_session_path
        to your account and check your button tag analytics from your dashboard.
        = link_to 'Click here >', dashboard_path
    .col-md-3

app/views/tags/tag_detailing.html.haml
.dashboard-box.text-center
  %h1
    Tag detailing

-if @like.present?
  .result{style: 'margin-bottom: 17%;'}
    %table.table
      %thead
        %tr
          %th
          %th Tag name
          %th Url
          %th Like count
          %th Tracking since
          %th Сountries
      %tbody
        %tr
          %th{:scope => "row"}
            %td
              = @like.tag_name
            %td
              = @like.url
            %td
              = @like_count
            %td
              = @date.created_at.strftime("%d %b %Y")
            %td
              = @countries