config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'

  get 'errors/internal_server_error'

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations'  }
  devise_scope :user do
    get '/users', to: 'users/registrations#new'
    get '/users/sign_out', to: 'users/sessions#destroy'
  end

  resources :tags, only: [:index, :show, :create] do
    member do
      post '/rename-tagname', action: 'rename_tag'
    end
  end
  resources :purchases, only: [:create, :index] do
    collection do
      get '/confirm-purchase', action: 'confirm_purchase'
    end
  end
  resources :subscribers, only: [:new, :create]
  post '/stripe/webhooks', to: "stripe#webhooks"

  get '/merchandise', to: 'site#merchandise', as: :merchandise
  get '/dashboard', to: 'site#dashboard', as: :dashboard
  get '/category/:name', to: 'site#category', as: :category
  get '/contact-us', to: 'site#contact_us', as: :contact_us
  post '/send-email', to: 'site#send_email', as: :sent_email
  get '/terms', to: 'site#terms', as: :terms
  get '/about-us', to: 'site#about_us', as: :about_us

  get '/like-button/:tag_name', to: 'peng_widget#tag_name'
  get '/like', to: 'peng_widget#like'
  get '/page-like-count', to: 'peng_widget#page_like_count'

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  root to: 'site#index', as: :root
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  before_action :authenticate_user!, only: :dashboard
  before_action :check_subscribtion, only: :dashboard

  def index
    @categories = Category.all.order('created_at ASC')
  end

  def dashboard
    @top_likes = Like.get_statistic.limit(30)
    @top_three_likes = @top_likes.first(3)
    @user_tags = current_user.tags.pluck(:tag_name).join(', ')

    @not_added_tags = Tag::TAGS_COUNT - current_user.tags.count

    @user_tags_statistic = current_user.get_user_statistic if current_user.tags.any?
    @result = Like.search_request(params[:search])
  end

  def send_email
    recipient_emails = ['online@gorillatheory.com', 'admin@certifiedpeng.com', 'henrychuks@hotmail.com']

    if params['g-recaptcha-response'].present?
      recipient_emails.each do |recipient|
        NotificationMailer.contact_us_notification(params[:options], recipient).deliver
      end
      flash[:notice] = 'Thank you for your feedback'
    else
      flash[:error] = 'Do not ignore reCAPTCHA checkbox'
    end
    redirect_to contact_us_path
  end

  def category
    @category = Category.find_by_name(params[:name])
  end

  def merchandise; end

  def contact_us; end

  def terms; end

  def about_us; end

  private

    def check_subscribtion
      redirect_to new_subscriber_path if current_user && !current_user.admin? && !current_user.subscriber?
    end
end

app/views/site/about_us.html.haml
.terms-box
  .row
    .col-md-2
    .col-md-8
      %h3.text-center
        About Us
      %br
      %p
        The Certified Peng platform technology and team is brought to you by Gorilla Theory Labs - the founder of the
        = link_to 'Gorilla Theory', 'http://www.gorillatheory.com', title: 'Gorilla Theory Project Management', target: '_blank'
        product delivery framework.
      %p
        The team have been delivering technology platforms and digital marketing
        campaigns for clients such as NHS Choices, Disney, Adidas and Nike, Volvo,
        Barclaycard, NBC Universal, AOL, and Pepsi. We have put all this fancy on
        the job experience and book learning into the Certified Peng platform - a
        proudly British adjective and ratings metric. The initial focus is the
        millennial demographic, but pengness is not ageist - we love everybody.
      %p
        Join the Peng bandwagon and start rating your products and content with Certified Peng
      %p
        Check the
        = link_to 'Peng Creps blog', 'http://www.pengcreps.co.uk', target: '_blank', title: 'Peng Creps'
        for trainers and sports footwear new.
      %p
        We Snap the funny, zany, the crazy moments. We live our best life on Insta. When you see someone or something
        peng, then capture that pengness with the
        = link_to 'Peng Cam app.', 'http://www.pengcam.co.uk', target: '_blank', title: 'Peng Cam app'
        Search for 'peng cam' in your appstore.
      %br
      %br
      .text-center
        = image_tag 'phil-man-tshirt.jpg'
    .col-md-2

app/views/site/category.html.haml
.image-container
  .row
    .col-md-12
      .image-content.text-center
        %h2
          = @category.name.capitalize
        - if @category.name == 'fashion'
          = image_tag 'chioma-jade.jpg', class: 'image-box-large', style: 'transform: scaleX(-1);'
        - elsif @category.name == 'retail'
          = link_to 'https://www.amazon.co.uk/gp/product/B07XRPPW5B/ref=as_li_tl?ie=UTF8&camp=1634&creative=6738&creativeASIN=B07XRPPW5B&linkCode=as2&tag=ebonyreads-21&linkId=e202fb521b2cb9f433d6250215d77dda', target: '_blank' do
            = image_tag 'iphone-11.jpg', class: 'image-box-large'
        - elsif @category.name == 'life'
          %iframe{allowfullscreen:  "", frameborder: "0", src: "//www.youtube.com/embed/89CUc8aa8xQ", class: 'life-video-content'}

.text-container
  .row
    .container
      .col-md-2
      .col-md-8
        .category-desc
          - if @category.name == 'fashion'
            %h3.text-center
              Certified Peng Merch
            %br
            %b
              Get peng-ready for 2020! Introduction SALE:
              %font{color: "#bf3939"} £30 (inc. VAT)
            (
            %strike £35
            )
            %b
              NB: Postage: £3.75 (Total Price:
              = succeed ")" do
                %font{:color => "#bf3939 "} £33.75

            %br
            %br
            %p
              The official, exclusive, Certified Peng T-Shirt (<b title="the Certified Peng t-shirt">the Cee Pee Tee</b>) is available for the discerning fashionista, the debonair mandem, the peng, and the aspirational peng!
            %p
              It's available exclusively from this Certified Peng website and comes in White, is 100% cotton, with twin-needle sleeves.
            %p
              %strog Stand out from the crowd and make a statement. It's a conversation starter! Get yours today - buy now below
            %p
              We have womens (small, medium) and mens (medium and large) at the moment.
            %p
              Ladies, the men's sizes make peng nighties (they look much better than his hoodie, for real!).

            %p
              %span
                %b Womens' Small
              (
              %a{class: 'buy-item', data: {item: 'Womens Small'}} buy now >
              )
              %b Womens' Medium
              (
              %a{class: 'buy-item', data: {item: 'Womens Medium'}} buy now >
              )
            %p
              %span
                %b Mens' Medium
              (
              %a{class: 'buy-item', data: {item: 'Mens Medium'}} buy now >
              )
              %b Mens' Large
              (
              %a{class: 'buy-item', data: {item: 'Mens Large'}} buy now >
              )
            %br
            .text-center
              = image_tag 'karl-leigh.jpg'
            .stripe-box
              = image_tag('pay-with-stripe.jpg', :class => "main-logo")
            %hr
          - elsif @category.name == 'retail'
            %b
              %p.text-center
                Apple iPhone 11 (128GB) - Black
            %br
            %p
              2020 - The year of the slow-mo selfie (get ready for the jiggle!)
            %br
            .text-center
              %iframe{allowfullscreen:  "", frameborder: "0", src: "//www.youtube.com/embed/KEc3aGjN228", class: 'life-video-content'}
            %br
            %p
              Apple has finally upped their camera game with the 11. Triple camera
              and slow-mo capability (Baywatch Cam!). If tings ain't peng at regular
              speed, slow things down.
            %br
            %ul
              %li 6.1-inch Liquid Retina HD LCD display
              %li Water and dust resistant (2 metres for up to 30 minutes, IP68)
              %li Dual-camera system with 12MP Ultra Wide and Wide cameras; Night mode, Portrait mode, and 4K video up to 60fps
              %li 12MP TrueDepth front camera with Portrait mode, 4K video, and Slo-Mo
              %li Face ID for secure authentication and Apple Pay
              %li A13 Bionic chip with third-generation Neural Engine
              %li Fast-charge capable
              %li Wireless charging
            %br
            %p
              Buy NOW on Amazon
              = link_to 'Apple iPhone 11 (128GB) - White', 'https://www.amazon.co.uk/gp/product/B07XRPPW5B/ref=as_li_tl?ie=UTF8&camp=1634&creative=6738&creativeASIN=B07XRPPW5B&linkCode=as2&tag=ebonyreads-21&linkId=e202fb521b2cb9f433d6250215d77dda'
              %img{:alt => "Apple iPhone 11", :border => "0", :height => "1", :src => "//ir-uk.amazon-adsystem.com/e/ir? t=ebonyreads-21&l=am2&o=2&a=B07XRPPW5B", :style => "border:none !important; margin:0px !important;", :width => "1"}/
            %br
            %strong Peng or Nah?
            %br
            %br
            %p
              The Balenciaga Tyrex sneaker...with the square toe-end...come on...they are Ballys'
              but are these ahead of the times or Certified Peng? They are Bally priced, of course.
              Take a look for yourselves at the
              = link_to 'Bally website >', 'https://www.balenciaga.com/gb/tyrex-shoes_cod11840115ff.html#/gb/all/tyrex-shoes', title: 'Bally Tyrex Sneaker', target: '_blank'
            %br
            .text-center
              = link_to 'https://www.balenciaga.com/gb/tyrex-shoes_cod11840115ff.html#/gb/all/tyrex-shoes', title: 'Bally Tyrex Sneaker', target: '_blank' do
                = image_tag 'bally-tyrex-sneaker.jpg', title: 'Bally Tyrex Sneaker'
            %hr
            .row
              .col-md-12.text-center
                .like-content
                  %p
                    You like the content? Click the button...
                .sinatra-like-button
                  %script{:src => "https://www.certifiedpeng.com/like-button/certified-peng-retailpage", :type => "text/javascript"}
          - elsif @category.name == 'life'
            %b
              %p.text-center
                Grime goes global
                %br Drill becomes mainstream?
            %br
            %p
              It's 2020 and Grime continues to evolve and break barriers and records. Main man Stormzy
              moves on from headlining at Glastonbury 2019 to his first world tour. The main European
              leg is before Brexit kicks in - smart move! Tickets available from
              = link_to 'the Stormzy website.', 'https://www.stormzy.com/#tourSection', target: '_blank', title: 'Stormzy World Tour 2020'
            %p
              J Hus is back with a banger of a new album ('Big Conspiracy') featuring collabos with
              Koffee, Burna Boy among others. Chart success and more respect should follow.
            %p
              How high will new star Aitch rise this year? He's moving from underground to mainstream.
              Will he convert the hardcore grime massive? Only time and consistently fire bars will tell.
            %p
              Which UK brand is utilising grime music and culture the best? Let's see what JD Sports and
              Fashion do in 2020, and Ikea (another peng TV advert to follow the
              = link_to '2019 Christmas advert?', 'https://www.youtube.com/watch?v=w0EKS2YfLc0', target: '_blank', title: '2019 Ikea Christmas TV advert'
            %p
              %strong Tip for the UK Grime Scene:
              Bring the top talent together for a tour and UK showcases or festivals. Brand the genre
              to sell to the world. Come Brexit, Brits need to have more bargaining power to benefit Brits.
            %hr
            .row
              .col-md-12.text-center
                .like-content
                  %p
                    You like the content? Click the button...
                .sinatra-like-button
                  %script{:src => "https://www.certifiedpeng.com/like-button/certified-peng-lifepage", :type => "text/javascript"}

.social-links
  .container
    .row
      .col-md-3.text-center
        %p
          = link_to "#", onclick: 'share_facebook(event);', class:'click' do
            Share Facebook
      .col-md-3.text-center
        %p
          %a{:href => "whatsapp://send?text=Share on whatsapp"} Share on WhatsApp
      .col-md-3.text-center
        %p
          = link_to '#', onclick: 'share_twitter(event);', class:'click' do
            %script{ type: "text/javascript", src:  "//newsharecounts.s3-us-west-2.amazonaws.com/nsc.js"}
            Share Twitter
      .col-md-3.text-center
        %p
          %a{href: "http://www.linkedin.com/shareArticle?mini=true&amp;url=https://simplesharebuttons.com", target: '_blank'} Share on LinkedIn
    %hr


.script-container
  .container
    .row
      .col-md-2
      .col-md-8
        .panel-group
          .panel.panel-default
            .panel-body
              %h4.text-center
                Get the Certified Peng button for your content:
            .panel-heading{style: 'color: #615e5e; font-size: 15px;'}
              = "<div class='sinatra-like-button'>"
              %br
              = "  <script src='https://www.certifiedpeng.com/like-button/TAG-NAME' type='text/javascript'></script>"
              %br
              = '</div>'
      .col-md-2



:javascript
  function share_facebook() {
    event.preventDefault();
    window.open("https://www.facebook.com/dialog/feed?app_id=1102341536470522&name=CertifiedPeng&display=popup&link=http://certifiedpeng.com&description=Share this amazing service!",'popup','height=500,width=500')
  }
  function share_twitter(event) {
    event.preventDefault();
    window.open("http://twitter.com/share?url=#{ENV['HOST']}&text=Share this amazing service!", 'twitterwindow', 'height=450, width=550, top='+($(window).height()/2 - 225) +', left='+$(window).width()/2 +', toolbar=0, location=0, menubar=0, directories=0, scrollbars=0');
  }

app/views/site/contact_us.html.haml
%h1.text-center Contact Us

.row
  .col-lg-4.col-md-3.col-xs-0
  .col-lg-4.col-md-6.col-xs-12
    = form_tag sent_email_path, class: 'form-box' do
      .form-group
        = label_tag :name
        = text_field_tag 'options[name]', nil, class: 'form-control', placeholder: 'Enter name'
      .form-group
        = label_tag 'Email address'
        = email_field_tag 'options[email]', nil, class: 'form-control', 'aria-describedby': "emailHelp", placeholder: 'Enter email', required: true
      .form-group
        = label_tag :telephone
        = telephone_field_tag 'options[telephone]',nil, class: 'form-control'
      .form-group
        = label_tag 'Reason for Contact'
        = select_tag 'options[reason]', options_for_select(['Advertising', 'Dashboard Support', 'Analytics', 'Peng Suggestion']), class: 'form-control'
      .form-group
        = label_tag :message
        = text_area_tag 'options[message]',nil,  rows: '3', class: 'form-control', required: true
      .form-group
        .recaptcha
          = recaptcha_tags
      = submit_tag 'Send', class: 'btn btn-primary', style: 'width: 100%'
  .col-lg-4.col-md-3.col-xs-0

app/views/site/dashboard.html.haml
.purchases-title
  %h1
    Your Dashboard

.search-box-text.text-center
  %p
    Enter url or tag in search box:

.row
  .col-lg-4.col-md-3.col-xs-2
  .col-lg-4.col-md-6.col-xs-8
    = form_tag dashboard_path, method: :get do
      .input-group
        = text_field_tag 'search', nil, placeholder: "Search for...", class: 'form-control'
        %span.input-group-btn
          = submit_tag 'Search',class: 'btn btn-default'
  .col-lg-4.col-md-3.col-xs-2

- if !@result.nil?
  - if @result.empty?
    .container
      .row
        .col-md-2
        .col-md-8
          %br
          .nothing-found.text-center
            Sorry, nothing found. Try it again...
        .col-md-2
  - else
    .dashboard-box.text-center
      %h3
        Search result:
    .result
      .container
        .row
          .col-md-12
            %table.table
              %thead
                %tr
                  %th
                  %th Url
                  %th Tag name
                  %th Like count
                  %th Tracking since
              %tbody
                - @result.each do |r|
                  %tr
                    %th{:scope => "row"}
                      %td
                        = r[:url]
                      %td
                        = r[:tag_names]
                      %td
                        = r[:count]
                      %td
                        = r[:date]

.dashboard-box.text-center
  %h3
    Your Certified Peng analytics:
-if @user_tags_statistic.present?
  .result
    .container
      .row
        .col-md-12
          %table.table
            %thead
              %tr
                %th
                %th Tag name
                %th Url
                %th Like count
                %th Tracking since
                %th Countries
            %tbody
              - @user_tags_statistic.each do |statistic|
                %tr.link-tr
                  %th{:scope => "row"}
                    %td
                      = statistic.tag_name
                    %td
                      = statistic.url
                    %td
                      = statistic.like_count
                    %td
                      = statistic.created_at.strftime("%d %b %Y")
                    %td
                      = statistic.countries.split(', ').uniq.join(', ')
- else
  .result
    .row
      .col-md-2
      .col-md-8.text-center
        You entered the tag
        %b '#{@user_tags}'
        when you registered. You have #{@not_added_tags} more tags in your allowance
        %br
        Add another tag now:
        = link_to 'click here >', tags_path
      .col-md-2

- if !current_user.admin?
  .dashboard-box.text-center
    %h3
      Top 3 most clicked:
  -if @top_three_likes.present?
    .result
      .container
        .row
          .col-md-12
            %table.table
              %thead
                %tr
                  %th
                  %th Tag name
                  %th Url
                  %th Total count of clicks
              %tbody
                - @top_three_likes.each do |top|
                  %tr
                    %th{:scope => "row"}
                      %td
                        = top.tag_name
                      %td
                        = top.url
                      %td
                        = top.like_count

- if current_user.admin?
  .dashboard-box.text-center
    %h3
      Top 30 most clicked:
  -if @top_likes.present?
    .result
      .container
        .row
          .col-md-12
            %table.table
              %thead
                %tr
                  %th
                  %th Tag name
                  %th Url
                  %th Total count of clicks
              %tbody
                - @top_likes.each do |top|
                  %tr
                    %th{:scope => "row"}
                      %td
                        = top.tag_name
                      %td
                        = top.url
                      %td
                        = top.like_count

app/views/site/index.html.haml
.image-container
  .container
    .row
      - @categories.each do |category|
        .col-md-4.text-center
          %h2{style: 'font-weight: bold;'}
            = category.name.capitalize
          = link_to category_path(category.name) do
            - if category.name == 'life'
              = image_tag 'home_life.jpg', class: 'image-box-small'
            - elsif category.name == 'fashion'
              = image_tag 'home_merch-girl.jpg', class: 'image-box-small'
            - else
              = image_tag 'home_retail.jpg', class: 'image-box-small'
          %h3{style: 'font-weight: bold;'}
            = link_to 'Check This Out >', category_path(category.name)
    %hr

.script-container
  .container
    .row
      .col-md-2
      .col-md-8
        .panel-group
          .panel.panel-default
            .panel-body{style: 'padding-bottom: 0px;'}
              %h4.text-center.bold
                Measure Pengness on Your Website
            %hr
            .panel-body{style: 'padding-top: 0px;'}
              %h4.text-center
                Get the Certified Peng button for your content:
            .panel-heading{style: 'color: #615e5e; font-size: 15px;'}
              %br
              = "<div class='sinatra-like-button'>"
              %br
              = "<script src='https://www.certifiedpeng.com/like-button/YOUR-TAG-HERE' type='text/javascript'></script>"
              %br
              = '</div>'
      .col-md-2
.button-demo
  .container
    .row
      .col-md-12.text-center
        %b
          %p
            You like the content? Click the button...
        %br
        .sinatra-like-button
          %script{:src => "https://www.certifiedpeng.com/like-button/certified-peng-homepage", :type => "text/javascript"}
    %hr

.text-container
  .container
    .row
      .col-md-12
        .tag-content
          %p
            %p
              %b How To:
            %b Step 1:
            Copy and paste the code snippet above
            %br
            %b Step 2:
            Place the code where you want the Certified Peng button to appear on your web page
            %br
            %b Step 3:
            Upload your web page and watch the clicks count increase
            %br
            %b NB:
            %span
              You can have a Certifed Peng button without adding having a tracking account, but you will not be able to access the
              = link_to 'tracking dashboard', new_user_session_path
              where you can create specific tags for campaigns or specific content
            %br
            %b Advanced - for tag tracking
            %br
            %b Step 4:
            %span
              = link_to 'Register', new_user_registration_path
              for a Certified Peng tracking account:
              = link_to 'click here >', new_user_registration_path
            %br
            %b Step 5:
            %span
              = link_to 'Login', new_user_session_path
              to your account and check your button tag analytics from your dashboard.
              = link_to 'Click here >', dashboard_path
    %hr

.text-container
  .container
    .row
      .col-md-12
        .peng-letters
          %p Phenomenal
          %p Excellent
          %p Notable
          %p Gorgeous

        %br
          Certified Peng is a new popularity and aesthetics metric to rate content and products. The Certified Peng platform lets content and product owners, and retailers pinpoint what content is trending as peng (news, images, video, products).
        %br
          Add the Certified Peng button to your content and find out what is trending and what is popular in terms of news and products and snapshots of life. Engage with Generation Z millennials and older (young at heart, with their finger on the pulse) audiences.
        %br
          Use the Certified Peng like button to drive interest in your product campaigns, content, products, or vanity snapshots. We have a dashboard that gives a closer look at who is liking your content and where. Join the Certified Peng network today.
        %br

app/views/site/merchandise.html.haml
.image-container
  .row
    .col-md-12
      .image-content.text-center
        %h2
          Fashion
        .category-image
          = image_tag 'merch-girl.jpg', class: 'image-box-large'


.text-container
  .row
    .container
      .col-md-2
      .col-md-8
        %h3.text-center
          Certified Peng Fashion
        %br
        %p
          <b>ALL stock introduction SALE: <font color="#bf3939 ">&#163;25 (inc. VAT)</font></b> ( <strike>&#163;35</strike> ) <b>NB: Postage: &#163;3.75 (Total Price: <font color="#bf3939 ">&#163;28.75</font>)</b>
        %p
          The official, exclusive design Certified Peng T-Shirt (the Cee Pee Tee) is available for mass consumption by the peng and aspirational peng! White, 100% cotton, twin-needle sleeves. Stand out from the crowd and make a statement this summer. <b>Get yours today.</b>
        %p
          We have womens (medium and large) and mens (large and XL) at the moment. Don't read anything in to those sizes...that's all that's left.
        %p
          %b
            Washing instructions:
        %p
          Machine wash warm (inside out), with whites wash. Tumble dry medium.
        %br
        %p
          %span
            %b Womens' Medium
          (
          %a{class: 'buy-item', data: {item: 'Womens Medium'}} buy now >
          )
          %b Womens' Large
          (
          %a{class: 'buy-item',data: {item: 'Womens Large'}} buy now >
          )
        %p
          %span
            %b Mens' Large
          (
          %a{class: 'buy-item', data: {item: 'Mens Large'}} buy now >
          )
          %b Mens' Extra Large
          (
          %a{class: 'buy-item', data: {item: 'Mens Extra Large'}} buy now >
          )
        .stripe-box
          = image_tag('pay-with-stripe.jpg', :class => "stripe-logo")
      .col-md-2

.social-links
  .container
    .row
      .col-md-4.text-center
        %p
          = link_to "#", onclick: 'share_facebook(event);', class:'click' do
            Share Facebook
      .col-md-4.text-center
        %p
          %a{:href => "whatsapp://send?text=Share on whatsapp"} Share on WhatsApp
      .col-md-4.text-center
        %p
          = link_to '#', onclick: 'share_twitter(event);', class:'click' do
            %script{ type: "text/javascript", src:  "//newsharecounts.s3-us-west-2.amazonaws.com/nsc.js"}
            Share Twitter
    %hr

.script-container
  .container
    .row
      .col-md-2
      .col-md-8
        .panel-group
          .panel.panel-default
            .panel-body
              %h4.text-center
                Get the Certified Peng button for your content:
            .panel-heading{style: 'color: #615e5e; font-size: 15px;'}
              = "<div class='sinatra-like-button'>"
              %br
              = "  <script src='https://www.certifiedpeng.com/like-button/TAG-NAME' type='text/javascript'></script>"
              %br
              = '</div>'
      .col-md-2

:javascript
  function share_facebook() {
    event.preventDefault();
    window.open("https://www.facebook.com/dialog/feed?app_id=1102341536470522&name=CertifiedPeng&display=popup&link=http://certifiedpeng.com&description=Share this amazing service!",'popup','height=500,width=500')
  }
  function share_twitter(event) {
    event.preventDefault();
    window.open("http://twitter.com/share?url=#{ENV['HOST']}&text=Share this amazing service!", 'twitterwindow', 'height=450, width=550, top='+($(window).height()/2 - 225) +', left='+$(window).width()/2 +', toolbar=0, location=0, menubar=0, directories=0, scrollbars=0');
  }