config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'

  get 'errors/internal_server_error'

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations'  }
  devise_scope :user do
    get '/users', to: 'users/registrations#new'
    get '/users/sign_out', to: 'users/sessions#destroy'
  end

  resources :tags, only: [:index, :show, :create] do
    member do
      post '/rename-tagname', action: 'rename_tag'
    end
  end
  resources :purchases, only: [:create, :index] do
    collection do
      get '/confirm-purchase', action: 'confirm_purchase'
    end
  end
  resources :subscribers, only: [:new, :create]
  post '/stripe/webhooks', to: "stripe#webhooks"

  get '/merchandise', to: 'site#merchandise', as: :merchandise
  get '/dashboard', to: 'site#dashboard', as: :dashboard
  get '/category/:name', to: 'site#category', as: :category
  get '/contact-us', to: 'site#contact_us', as: :contact_us
  post '/send-email', to: 'site#send_email', as: :sent_email
  get '/terms', to: 'site#terms', as: :terms
  get '/about-us', to: 'site#about_us', as: :about_us

  get '/like-button/:tag_name', to: 'peng_widget#tag_name'
  get '/like', to: 'peng_widget#like'
  get '/page-like-count', to: 'peng_widget#page_like_count'

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  root to: 'site#index', as: :root
end

app/models/subscriber.rb
class Subscriber < ActiveRecord::Base
  belongs_to :user

  def self.subscribe(user, stripe_token)
    begin
      subscription = user.subscriber || user.create_subscriber

      if subscription.stripe_id
        stripe_customer = Stripe::Customer.retrieve(subscription.stripe_id)
        stripe_customer.source = stripe_token
        stripe_customer.save
      else
        stripe_customer = Stripe::Customer.create(
          card: stripe_token,
          email: user.email,
          description: "Customer userID - #{user.id}"
        )
      end

      if stripe_customer
        stripe_subscription = Stripe::Subscription.create(
          customer: stripe_customer.id,
          plan: 'monthyplan'
        )

        if stripe_subscription && stripe_subscription.id
          subscription.update_attributes(end_date: Time.at(stripe_subscription.current_period_end), stripe_id: stripe_customer.id, subscribed: true)
        end
      end
      return 'success'
    rescue Stripe::CardError => e
      return e
    rescue Stripe::InvalidRequestError => e
      return e
    rescue => e
      return e
    end
  end
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  before_action :authenticate_user!

  def new
  end

  def create
    subscription = Subscriber.subscribe(current_user, params[:stripeToken])

    if subscription == 'success'
      flash[:notice] = 'Your payment has been successfully processed'
      redirect_to dashboard_path
    else
      flash[:error] = subscription
      redirect_to new_subscriber_path
    end
  end
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/views/subscribers/new.html.haml
.row
  .col-md-2
  .col-md-8
    %h1.text-center
      CertifiedPeng subscription
    .pay-box
      %p
        You now have a Certified Peng analytics account but if you want to track the number of clicks your tag is receiving you need to have a Pro account (this costs £10.00 a month for as long as you need to track a tag)
      %h3
        %b Subscribe to Certified Peng Analytics now
      %br
      = link_to 'The Certified Peng Dashboard Terms >', terms_path
      .confirm-terms.text-center
        = check_box('terms-pay', 'acepted', class: 'terms-confirm')
        I agree with the Certified Peng Terms (please check the box to proceed)
      = form_tag subscribers_path do
        %script.stripe-button{data: {email: current_user.email, amount: '1000', currency: 'GBP', name: 'Monthly Plan', description: 'CertifiedPeng subscription', key: Rails.configuration.stripe[:publishable_key], locale: 'auto'},checkout:{label: 'TEXT'}, src: 'https://checkout.stripe.com/checkout.js'}
      .stripe-box
        = image_tag('pay-with-stripe.jpg', :class => "stripe-logo")
  .col-md-2
%br